version: "3"

networks:
  bid-scheduler:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - bid-scheduler

  redis:
    image: redis:6
    ports:
      - "6382:6379"
    networks:
      - bid-scheduler

  php:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - ./server:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - bid-scheduler
