version: "3"

networks:
  todo:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - todo

  mysql:
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - todo

  redis:
    image: redis:6
    ports:
      - "6382:6379"
    networks:
      - todo

  php:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - todo
